if __name__ == "__main__":
    print("=== HASH TABLE DEMO ===")
    ht = HashTable()
    ht.insert("apple", 1)
    ht.insert("banana", 2)
    ht.insert("cherry", 3)
    ht.insert("date", 4)
    ht.insert("elderberry", 5)
    ht.insert("fig", 6)          
    print("HashTable contents:", ht)
    print("get('banana') =", ht.get("banana"))
    print("contains('fig') =", ht.contains("fig"))
    print("size() =", ht.size())           
    ht.delete("cherry")
    print("After deleting cherry, size =", ht.size())